### ISSUE TITLE
python .\faces.py error

### ISSUE THREAD

**Issue by ADBYITS** [codingforentrepreneurs/OpenCV-Python-Series#1]
Hi guys
I just got all the code and thought i got all the way though the FR stuff but i keep getting a error when i run faces.py 

PS C:\Users\ADBY\Desktop\Coding\OpenCV-Python-Series-master\src> python .\faces.py
OpenCV Error: Unspecified error (File can't be opened for reading!) in cv::face::FaceRecognizer::read, file C:\projects\opencv-python\opencv_contrib\modules\face\src\facerec.cpp, line 61
Traceback (most recent call last):
  File ".\faces.py", line 11, in <module>
    recognizer.read("trainner.yml")
cv2.error: C:\projects\opencv-python\opencv_contrib\modules\face\src\facerec.cpp:61: error: (-2) File can't be opened for reading! in function cv::face::FaceRecognizer::read

**Comment by jakuta-tech** [comment]
check that traiiner.yml exists. It was moved to the folder "recognizers" and renamed face-trainner.yml in the repo

**Comment by jakuta-tech** [comment]
you need to make sure in the images folder that there's a subdirectory. That subdirectory should have images of you in it.  Run face-trainer.py and then run faces.py. It will find the directory and then the label will be put onto the image.

**Comment by ADBYITS** [comment]
Yep done a that and ran the output and can see it seeing my folder and same
deal

**Comment by Mathanesh-Ramasamy** [comment]
File "face-train.py", line 21
    if label in label_ids:
                         ^
SyntaxError: invalid syntax
PS C:\Users\RAVI\desktop\dev>
line 21- if not label in label_ids:

how to solve this error?

**Comment by nandkumar1996** [comment]
OpenCV Error: Unspecified error (File can't be opened for reading!) in cv::face::FaceRecognizer::read, file C:\projects\opencv-python\opencv_contrib\modules\face\src\facerec.cpp, line 61
Traceback (most recent call last):
  File "faces.py", line 11, in <module>
    recognizer.read("trainner.yml")
cv2.error: C:\projects\opencv-python\opencv_contrib\modules\face\src\facerec.cpp:61: error: (-2) File can't be opened for reading! in function cv::face::FaceRecognizer::read

**Comment by codingforentrepreneurs** [comment]
Trainer was moved and code has been updated.

**Comment by bgnelson** [comment]
No worries.  Glad to help out,  you provided a great starting point.  Are you still experiencing issues?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ankithendre** [comment]
File ".\faces.py", line 11, in <module>
    recognizer.read("./recognizors/face-trainner.yml")
cv2.error: OpenCV(3.4.3) C:\projects\opencv-python\opencv_contrib\modules\face\src\facerec.cpp:61: error: (-2:Unspecified error) File can't be opened for reading! in function 'cv::face::FaceRecognizer::read'
what shoul i do?

**Comment by bgnelson** [comment]
Make sure the code is referencing the file name.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ankithendre** [comment]
thank you @bgnelson just had to rename folder

**Comment by Yanchobasil** [comment]
hi guys 
i got the code but when i run it i keep on getting 
error: OpenCV(3.4.1) C:\Miniconda3\conda-bld\opencv-suite_1533128839831\work\opencv_contrib-3.4.1\modules\face\src\facerec.cpp:61: error: (-2) File can't be opened for reading! in function cv::face::FaceRecognizer::read

**Comment by SparshMaheshwari** [comment]
Should the trainer.yml be empty ?
If not then what must be there in it ?

**Comment by hirenkhatri** [comment]
In OpenCV 3.3

load() is replaced by read()

save() is replaced by write()

**Comment by vijaychand118** [comment]
error: OpenCV(4.1.0) C:\projects\opencv-python\opencv_contrib\modules\face\src\facerec.cpp:61: error: (-2:Unspecified error) File can't be opened for reading! in function 'cv::face::FaceRecognizer::read'
will u please check it error
then tell me the solution

**Comment by hirenkhatri** [comment]
In OpenCV 3.3

load() is replaced by read()

save() is replaced by write()


Change your method acoding to your respected version of opencv

**Comment by samii-ullah** [comment]
Can any one tell me i am facing this issue. how to resolve this bug?

recognizer.read('trainer/trainer.yml')
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv_contrib\modules\face\src\facerec.cpp:61: error: (-2:Unspecified error) File can't be opened for reading! in function 'cv::face::FaceRecognizer::read'

**Comment by DeepaDev69** [comment]
I have the same problem but for writing in file. and i am using cv2.face.LBPHFaceRecognizer_create().write('trainer/trainer.yml')
it is still throwing error
please help!!!

**Comment by AlbandryNasser** [comment]
I still have the same issue 
recognizer.read("recognizers/face-trainner.yml")
cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv_contrib\modules\face\src\facerec.cpp:61: error: (-2:Unspecified error) File can't be opened for reading! in function 'cv::face::FaceRecognizer::read'

Please help!

**Comment by patelrinkesh24** [comment]
Just copy the folder given below in your main folder of Face-Recognition-Based-Attendance-System-master 

[TrainingImageLabel.zip](https://github.com/codingforentrepreneurs/OpenCV-Python-Series/files/4333772/TrainingImageLabel.zip)

**Comment by vanetoj** [comment]
patel when i use the face_recognizer.train(faces_pca, ids) it tells me "Expected 4, but was 2. in function 'train'" any ideas? thanks

**Comment by vanetoj** [comment]
> Just copy the folder given below in your main folder of Face-Recognition-Based-Attendance-System-master
> 
> [TrainingImageLabel.zip](https://github.com/codingforentrepreneurs/OpenCV-Python-Series/files/4333772/TrainingImageLabel.zip)
patel when i use the face_recognizer.train(faces_pca, ids) it tells me "Expected 4, but was 2. in function 'train'" any ideas? thanks

**Comment by salmonnella99** [comment]
Traceback (most recent call last):
  File "D:\face\faces.py", line 20, in <module>
    faces = face_cascade.detectMultiScale(gray, scaleFactor=1.5, minNeighbors=5)
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-rwld3ghi\opencv\modules\objdetect\src\cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'cv::CascadeClassifier::detectMultiScale'

anybody can tell me how i fixing this kind of error? at my first laptop it running well but when i move the code to my second laptop i got this error (sorry for my bad english)

**Comment by Ainsyafi** [comment]
line 6, in <module>
 recognizer.read('trainer/trainer.yml')   #load trained model
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-zeowd5_m/opencv_contrib/modules/face/src/facerec.cpp:61: error: (-2:Unspecified error) File can't be opene

anybody can tell me how i fixing this kind of error? i used os ubuntu

**Comment by MUHAMMAD-USAMA-ASHRAF** [comment]
Traceback (most recent call last):
  File "C:/Users/HP LAPTOPS/Desktop/AI project/Training.py", line 21, in <module>
    model.train(np.asarray(Training_Data), np.asarray(Labels))
cv2.error: OpenCV(4.0.1) C:\ci\opencv-suite_1573470242804\work\opencv_contrib-4.0.1\modules\face\src\lbph_faces.cpp:362: error: (-210:Unsupported format or combination of formats) Empty training data was given. You'll need more than one sample to learn a model. in function 'cv::face::LBPH::train'


Process finished with exit code 1
