### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by junaidleo** [codingforentrepreneurs/OpenCV-Python-Series#4]
Its showing me an error like this

![error](https://user-images.githubusercontent.com/42765066/44707832-350a1d00-aac3-11e8-9df6-13c4229d4ed6.jpg)
OpenCV Error: Bad argument (This LBPH model is not computed yet. Did you call the train method?) in cv::face::LBPH::predict, file C:\ci\opencv_1512685267089\work\opencv_contrib-3.3.1\modules\face\src\lbph_faces.cpp, line 400
Traceback (most recent call last):
  File "faces.py", line 31, in <module>
    id_, conf = recognizer.predict(roi_gray)
cv2.error: C:\ci\opencv_1512685267089\work\opencv_contrib-3.3.1\modules\face\src\lbph_faces.cpp:400: error: (-5) This LBPH model is not computed yet. Did you call the train method? in function cv::face::LBPH::predict

**Comment by codingforentrepreneurs** [comment]
Code has been updated. Please check.
