### ISSUE TITLE
faces.py 

### ISSUE THREAD

**Issue by nandkumar1996** [codingforentrepreneurs/OpenCV-Python-Series#5]
I am getting error
OpenCV Error: Unspecified error (File can't be opened for reading!) in cv::face::FaceRecognizer::read, file C:\projects\opencv-python\opencv_contrib\modules\face\src\facerec.cpp, line 61
Traceback (most recent call last):
  File "faces.py", line 11, in <module>
    recognizer.read("trainner.yml")
cv2.error: C:\projects\opencv-python\opencv_contrib\modules\face\src\facerec.cpp:61: error: (-2) File can't be opened for reading! in function cv::face::FaceRecognizer::read

**Comment by codingforentrepreneurs** [comment]
Code has been updated. Please check.
