### ISSUE TITLE
'cv::face::FaceRecognizer::read'

### ISSUE THREAD

**Issue by manisaiprasad** [codingforentrepreneurs/OpenCV-Python-Series#6]
Traceback (most recent call last):
  File "faces.py", line 11, in <module>
    recognizer.read("./recognizors/face-trainner.yml")
cv2.error: OpenCV(3.4.3) C:\projects\opencv-python\opencv_contrib\modules\face\src\facerec.cpp:61: error: (-2:Unspecified error) File can't be opened for reading! in function 'cv::face::FaceRecognizer::read'

**Comment by samyak1512** [comment]
juanaidleo pls give the whole syntax for it

**Comment by yashrastogi16** [comment]
So the issue here is in the path, the folder name is recognizers, which by mistake is written as recognizors in lineno. 11.

**Comment by Sajad134** [comment]
Thank you so much for pointing that out bro!

**Comment by codingforentrepreneurs** [comment]
Fixed in source code. Thanks everyone.

**Comment by Abhishek-N** [comment]
Referred the changed source code, yet this issue:
Traceback (most recent call last):
  File "faces.py", line 11, in <module>
    recognizer.read("./recognizers/face-trainner.yml")
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\core\src\persistence.cpp:719: error: (-49:Unknown error code -49) Input file is invalid in function 'cv::FileStorage::Impl::open'

**Comment by SidVer312** [comment]
I am still having the same problem

**Comment by patelrinkesh24** [comment]
Just copy below folder in your main folder of Face-Recognition-Based-Attendance-System-master its all...
[TrainingImageLabel.zip](https://github.com/codingforentrepreneurs/OpenCV-Python-Series/files/4333773/TrainingImageLabel.zip)

**Comment by afiqff8** [comment]
i have problem FacialMotionCapture_v2 + blender + opencv
link: https://github.com/jkirsons/FacialMotionCapture_v2

problem:
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\core\src\persistence.cpp:719: error: (-49:Unknown error code -49) Input file is invalid in function 'cv::FileStorage::Impl::open'

**Comment by Shankar-Aditya-OSS** [comment]
add the above zip file guys it works..

**Comment by Fazaljanan** [comment]
errortype: can only join an iterable.


how can i fix this error

**Comment by Fazaljanan** [comment]
#================face recognition==================
    def face_recog(self):
        def draw_boundray(img,classifier,scaleFactor,minNeighbors,color,text,clf):
            gray_image=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
            featuers=classifier.detectMultiScale(gray_image,scaleFactor,minNeighbors)

            coord=[]
            
            for (x,y,w,h) in featuers:
                cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)
                id,predict=clf.predict(gray_image[y:y+h,x:x+w])

                confidence=int((100*(1-predict/300)))

                conn = mysql.connector.connect(username='root', password='fazal123',host='localhost',database='face_recognition',port=3306)
                cursor = conn.cursor()

                cursor.execute("select Name from student where Student_ID="+str(id))
                n=cursor.fetchone()
               
                n="+".join(n)
               
                

                cursor.execute("select Roll_No from student where Student_ID="+str(id))
                r=cursor.fetchone()
                
                r="+".join(r)
                

                cursor.execute("select Student_ID from student where Student_ID="+str(id))
                i=cursor.fetchone()
               
                i="+".join(i)
                
                
               


                if confidence > 77:
                    cv2.putText(img,f"Student_ID:{i}",(x,y-80),cv2.FONT_HERSHEY_COMPLEX,0.8,(64,15,223),2)
                    cv2.putText(img,f"Name:{n}",(x,y-55),cv2.FONT_HERSHEY_COMPLEX,0.8,(64,15,223),2)
                    cv2.putText(img,f"Roll-No:{r}",(x,y-30),cv2.FONT_HERSHEY_COMPLEX,0.8,(64,15,223),2)
                    self.mark_attendance(i,r,n)
                else:
                    cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,255),3)
                    cv2.putText(img,"Unknown Face",(x,y-5),cv2.FONT_HERSHEY_COMPLEX,0.8,(255,255,0),3)    

                coord=[x,y,w,h]
            
            return coord
